apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopware.fullname" . }}-config
  labels:
    {{- include "shopware.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.shopware.env }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
