{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "shopware.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  selector:
    {{- include "shopware.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  {{- end }}
