{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "shopware.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    {{- include "shopware.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
  {{- end }}
