apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopware.fullname" . }}-secret
  labels:
    {{- include "shopware.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
